Place LDFLAGS after OBJECTS in compile command
I was getting errors like "undefined reference to `gzopen'", so I
found this:

http://stackoverflow.com/questions/9145177/undefined-reference-to-gzopen-error

which told me to put "-lz" after the object names. I tried making that
change in the Makefile, and it fixed things.